
service: flutter-aws-serverless
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  #region: us-west-2
  stage: dev
  profile: taehoon-flutter-study
  logs:
    websocket: true
  # iamRoleStatements:
  #   - Effect: "Allow"
  #     Action:
  #         - dynamodb:DescribeTable
  #         - dynamodb:Query
  #         - dynamodb:Scan
  #         - dynamodb:GetItem
  #         - dynamodb:PutItem
  #         - dynamodb:UpdateItem
  #         - dynamodb:DeleteItem
  #     Resource: "arn:aws:dynamodb:${self:provider.region}:*:*"
  
# iamRoleStatements:
#   - Effect: Allow
#     Action:
#       - "execute-api:ManageConnections"
#     Resource:
#       - "arn:aws:execute-api:*:*:**/@connections/*"

functions:
  connectionHandler:
    handler: handler.connectionHandler
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
  defaultHandler:
    handler: handler.defaultHandler
    events:
      - websocket: $default
  databaseStreamHandler:
    handler: handler.databaseStreamHandler
    events:
      - websocket:
          route: databaseStream
      # - stream:
      #     type: dynamodb
      #     batchSize: 1
      #     startingPosition: LATEST
      #     arn:
      #       Fn::GetAtt: [flutterSlsTable, StreamArn]
  databasePostHandler:
    handler: handler.databasePostHandler
    events:
      - http:
          path: ${self:service}/databasePost
          method: post
          cors: true
          request:
            template:
              application/json: >
                #set($inputRoot = $input.path('$'))
                {
                  "body": {
                    "randNum": $inputRoot.input.randNum,
                    "msg": $inputRoot.input.msg
                  }
                }

# CloudFormation template syntax from here on.
resources:
  Resources:
    flutterSlsTable:
      Type: AWS::DynamoDB::Table
      # DeletionPolicy: Retain
      Properties:
        TableName: flutterSlsTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: randNum
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: randNum
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_IMAGE